#!/bin/sh

branch_name=$(git symbolic-ref --short HEAD)

if ! echo "$branch_name" | grep -Eq '^(main|feature|bug|docs|chore|hotfix)/?[a-z0-9._-]*$'; then
  echo "❌ Invalid branch name: \"$branch_name\""
  echo "➡️  Use: main or feature/, bug/, docs/, chore/, hotfix/"
  exit 1
fi

