# CAN settings
BUS_INTERFACE = "pcan"
BUS_CHANNEL = "PCAN_USBBUS1"
BITRATE = 250000

AXIS0_NODE_ID = 0
AXIS1_NODE_ID = 1
NODE_IDS = (AXIS0_NODE_ID, AXIS1_NODE_ID)

# ODrive CAN Simple command IDs
CMD_HEARTBEAT = 0x01
CMD_SET_AXIS_STATE = 0x07
CMD_GET_ENCODER_ESTIMATES = 0x09
CMD_SET_INPUT_VEL = 0x0D

# ODrive axis states
AXIS_STATE_IDLE = 1
AXIS_STATE_CLOSED_LOOP_CONTROL = 8

# Control settings
LOOP_PERIOD = 0.05
CLOSED_LOOP_TIMEOUT = 5.0
CRUISE_VELOCITY = 5.0
VELOCITY_STEP = 2.0
MAX_VELOCITY = 35.0
RAMP_RATE = 1.0
ZERO_VELOCITY_THRESHOLD = 0.001

# Encoder polling / telemetry
TELEMETRY_PERIOD = 2
ENCODER_RESPONSE_TIMEOUT = 0.05
TELEMETRY_HOST = "127.0.0.1"
TELEMETRY_PORT = 5055
TELEMETRY_STALE_AFTER = 2.0
